### PR TITLE
Fix typo in spelling of "Notifications"

### PR DESCRIPTION
**Pull request by johnnyg**

### CODE REVIEW

**Comment by cfvescovo** [comment]
@simonmeusel Could you merge this PR?

**Comment by qmnl** [comment]
See #12

**Comment by qmnl** [comment]
Thank you for the PR, I actually fixed this type myself, but I'm currently unable to build the project, since the eonil/FileSystemEvents library is not compatible with the new version of XCode

**Comment by qmnl** [comment]
Released at https://github.com/simonmeusel/MuteSpotifyAds/releases

**Pull request merged**
